# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konsert',
            name='sceneNavn',
            field=models.CharField(default='Hovedscenen', max_length=250),
        ),
    ]
