# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_konsert_scenenavn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extend_user',
            options={'permissions': (('is_technican', 'Is technican'), ('is_manager', 'Is manager'))},
        ),
    ]
