# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170925_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extend_user',
            options={},
        ),
        migrations.AlterField(
            model_name='rigging',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
