# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170925_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konsert',
            old_name='a_navn',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='konsert',
            old_name='s_tidspunkt',
            new_name='tidspunkt',
        ),
    ]
