# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170925_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artister'},
        ),
        migrations.AlterModelOptions(
            name='extend_user',
            options={'verbose_name': 'Extend user', 'verbose_name_plural': 'Extend users'},
        ),
        migrations.AlterModelOptions(
            name='konsert',
            options={'verbose_name': 'Konsert', 'verbose_name_plural': 'Konserter'},
        ),
        migrations.AlterModelOptions(
            name='rigging',
            options={'verbose_name': 'Rigging', 'verbose_name_plural': 'Rigginger'},
        ),
    ]
